import os
from pathlib import Path


class ConfigurationManager:
    """Generate environment-driven configuration for new projects."""

    def generate(self, root):
        root = Path(root)
        config = root / "src" / "config"
        config.mkdir(parents=True, exist_ok=True)
        settings = config / "settings.py"
        settings.write_text(
            '''"""Generated by OAE. Secrets are supplied through the environment."""
import os

APP_NAME = os.getenv("APP_NAME", "Generated Application")
APP_ENV = os.getenv("APP_ENV", "development")
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///app.db")
SECRET_KEY = os.environ["SECRET_KEY"]
''',
            encoding="utf-8",
        )
        return settings
