from pathlib import Path


class ConfigurationManager:
    """
    Generates configuration files for new projects.
    """

    def generate(self, root):
        root = Path(root)

        config = root / "src" / "config"
        config.mkdir(parents=True, exist_ok=True)

        settings = config / "settings.py"

        settings.write_text(
'''"""
Generated by OAE
"""

APP_NAME = "Opportunity Radar Africa"
APP_ENV = "development"
DATABASE_URL = "sqlite:///app.db"
SECRET_KEY = "change-me"
'''
        )

        return settings
