"""
Kernel event names.
"""

SYSTEM_STARTING = "SYSTEM_STARTING"
SYSTEM_READY = "SYSTEM_READY"
SYSTEM_SHUTDOWN = "SYSTEM_SHUTDOWN"

MISSION_CREATED = "MISSION_CREATED"
MISSION_STARTED = "MISSION_STARTED"
MISSION_COMPLETED = "MISSION_COMPLETED"
MISSION_FAILED = "MISSION_FAILED"
