from pathlib import Path

from oae.core.project_specification import ProjectSpecification


class ExecutableApplicationGenerator:
    """
    Generates a runnable application from a ProjectSpecification.
    """

    def generate(self, root, specification: ProjectSpecification):
        root = Path(root)

        src = root / "src"
        src.mkdir(parents=True, exist_ok=True)

        main = src / "main.py"

        main.write_text(
f'''"""
Generated by OAE
"""

from api.health import health


def main():
    info = health()

    print("=" * 40)
    print(info["service"])
    print("Status:", info["status"])
    print("=" * 40)


if __name__ == "__main__":
    main()
'''
        )

        api = src / "api"
        api.mkdir(parents=True, exist_ok=True)

        (api / "__init__.py").write_text("")

        (api / "health.py").write_text(
f'''def health():
    return {{
        "status": "healthy",
        "service": "{specification.name}",
    }}
'''
        )

        return main
