from pathlib import Path

from oae.core.project_specification import ProjectSpecification


class ExecutableApplicationGenerator:
    """Generate a runnable FastAPI application with a stable health contract."""

    def generate(self, root, specification: ProjectSpecification):
        root = Path(root)
        src = root / "src"
        src.mkdir(parents=True, exist_ok=True)

        main = src / "main.py"
        main.write_text(
f'''"""Generated by OAE."""

from fastapi import FastAPI
from api.health import health

app = FastAPI(title="{specification.name}")


@app.get("/health")
def health_endpoint():
    return health()


def main():
    info = health()
    print("=" * 40)
    print(info["service"])
    print("Status:", info["status"])
    print("=" * 40)


if __name__ == "__main__":
    main()
''', encoding="utf-8")

        api = src / "api"
        api.mkdir(parents=True, exist_ok=True)
        (api / "__init__.py").write_text("", encoding="utf-8")
        (api / "health.py").write_text(
f'''def health():
    return {{
        "status": "healthy",
        "service": "{specification.name}",
    }}
''', encoding="utf-8")

        return main
