from pathlib import Path

from oae.core.project_specification import ProjectSpecification


class ReadmeGenerator:
    """
    Generates the project README.
    """

    def generate(self, root, specification: ProjectSpecification):
        root = Path(root)

        content = f"""# {specification.name}

## Description

{specification.description}

## Technology

- Language: {specification.language}
- Framework: {specification.framework}
- Database: {specification.database}

Generated by OAE.
"""

        path = root / "README.md"
        path.write_text(content)

        return path
