[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "oae-core"
version = "0.1.0"
description = "Open Autonomous Engineer Core Runtime"
authors = [
    { name = "Olori" }
]
requires-python = ">=3.11"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
