from pathlib import Path


class Executor:

    def write_readme(self, mission: str):

        content = f"""# Repository

Generated by OAE Core

## Mission

{mission}

This README was automatically created by OAE.
"""

        path = Path("README.md")
        path.write_text(content)

        return path
