from pathlib import Path

from oae.meta.generator_spec import GeneratorSpecification


class GeneratorBuilder:
    """
    Builds a new OAE generator from a specification.
    """

    def build(self, root, spec: GeneratorSpecification):
        root = Path(root)

        core = root / "src" / "oae" / "core"
        core.mkdir(parents=True, exist_ok=True)

        filename = (
            spec.name.replace("Generator", "").lower()
            + "_generator.py"
        )

        target = core / filename

        target.write_text(
f'''"""
Generated by OAE Meta Generator Engine
"""

from pathlib import Path


class {spec.name}:
    """
    {spec.description}
    """

    def generate(self, root):
        root = Path(root)

        return root
'''
        )

        return target
